openapi: 3.0.0
info:
  title: Combined API Specification
  version: 1.0.0
paths:
  /health:
    get:
      summary: Get Health
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /users/{userId}/orders:
    get:
      summary: Get User Orders
      parameters:
      - in: path
        name: userId
        required: true
        schema:
          type: string
        description: The ID of the user
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        _id:
                          type: string
                        userId:
                          type: string
                        items:
                          type: array
                          items:
                            type: object
                            properties:
                              _id:
                                type: string
                              quantity:
                                type: integer
                              userId:
                                type: string
                              coffeeId:
                                type: string
                              createdAt:
                                type: string
                                format: date-time
    post:
      summary: Create User Order
      parameters:
      - in: path
        name: userId
        required: true
        schema:
          type: string
        description: The ID of the user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                items:
                  type: array
                  items:
                    type: object
                    properties:
                      quantity:
                        type: integer
                      coffeeId:
                        type: string
                    required:
                    - quantity
                    - coffeeId
              required:
              - items
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      _id:
                        type: string
                      userId:
                        type: string
                      items:
                        type: array
                        items:
                          type: object
                          properties:
                            _id:
                              type: string
                            quantity:
                              type: integer
                            userId:
                              type: string
                            coffeeId:
                              type: string
                            createdAt:
                              type: string
                              format: date-time
    delete:
      summary: Delete All User Orders
      parameters:
      - in: path
        name: userId
        required: true
        schema:
          type: string
        description: The ID of the user
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      acknowledged:
                        type: boolean
                      deletedCount:
                        type: integer
  /users/{userId}/orders/{orderId}:
    delete:
      summary: Delete Order By Id
      parameters:
      - in: path
        name: userId
        required: true
        schema:
          type: string
        description: The ID of the user
      - in: path
        name: orderId
        required: true
        schema:
          type: string
        description: The ID of the order
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      acknowledged:
                        type: boolean
                      deletedCount:
                        type: integer
components:
  schemas: {}
